# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 11:44
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase', '0007_auto_20170526_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=2000)),
                ('phone_number', models.CharField(max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 29, 11, 44, 22, 923195, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 29, 11, 44, 22, 923869, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='like',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 29, 11, 44, 22, 924597, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 29, 11, 44, 22, 925196, tzinfo=utc)),
        ),
    ]
