# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 19:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_auto_20170529_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='profilepic',
            field=models.CharField(default='../../static/purchase/images/', max_length=200),
        ),
        migrations.AlterField(
            model_name='cart',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 29, 19, 12, 14, 965087, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 29, 19, 12, 14, 965888, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='like',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 29, 19, 12, 14, 966858, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 29, 19, 12, 14, 970869, tzinfo=utc)),
        ),
    ]
